- url: /
  template: index.html
  context:
    name: Thomas Day
    icon: assets/favicon.ico
    about:
      firstName: Thomas
      lastName: Day
      state: Michigan
      phone: (586) 945-8054
      email: tvday@umich.edu
      profilePictureLink: assets/profile.jpeg
      resumeLink: pages/Thomas_Day_resume.pdf
      resumeDate: Jan 2024
      linkedInLink: https://www.linkedin.com/in/tvday/
      gitHubLink: https://github.com/tvday
      about: >
        I am a recent graduate from the University of Michigan. 
        I have a dual degree in Computer Science and Business Administration through the Stephen M. Ross School of Business. 
        I have interests in software engineering and using machine learning to solve business problems. 
        I have a passion for furthering education especially expanding computer science education. 
        On the side, I like to play in Unity to hopefully one day release a full game on Steam.
    skills:
      - name: Python
        icon: python.png
      - name: Go
        icon: go.png
      - name: C++
        icon: cpp.png
      - name: C
        icon: c.png
      - name: C#
        icon: c_sharp2.png
      - name: R and RStudio
        icon: r.png
      - name: "SQL Languages: MySQL, Oracle, Postgres"
        icon: sql.png
      - name: Git
        icon: git.png
      - name: HTML
        icon: html.png
      - name: CSS
        icon: css.png
      - name: JavaScript
        icon: javascript.png
      - name: Bash
        icon: bash.png
      - name: RegEx
        icon: regex.png
      - name: Apache Spark
        icon: spark.png
      - name: Pandas Python Library
        icon: pandas.png
      - name: Unix-Like OS's
        icon: linux.png
      - name: AWS
        icon: aws.png
      - name: Excel and Microsoft Office Suite
        icon: excel.png
      - name: React
        icon: react.png
      - name: Unity
        icon: unity.png
    experience:
      - title: Software Engineer Intern
        company: NCR Corporation
        startDate: May 2022
        endDate: August 2022
        location: Atlanta, GA
        description: >
          Worked with a team of interns on a summer long project to create an order status board and recreate a self-service kiosk application.
          The purpose was to improve the user experience for both direct customers and end-users.
          I lead the other interns, especially after the full-time lead left, in architecting and implementing the project.
          I worked with the front end developers to create a WebSocket server and REST API using Go, leveraging the Backend-For-Frontend design pattern.
          I also gathered data through testing and experimenting to redesign the current API integration to support future work 
          and even showcased a prototype that would address technical debt.
      - title: Research Assistant
        company: Michigan Ross School of Business
        startDate: May 2020
        endDate: September 2020
        location: Ann Arbor, MI
        description: >
          Worked with a marketing Ph.D. student under Professors Aradhna Krishna, S Sriram, and H. V. Jagadish to study effective brand use on social media.
          I used the Apache Spark library in Python and Twitter's API to analyze terabytes of Twitter data on a High Performance Computing cluster.
          I filtered tweets by text content using RegEx, content metrics, user data, and nested retweets’ data to retrieve the wanted tweets for the research.
          A large part of my role was reviewing brand awareness literature and peer reviewed papers in social media context to inform and direct research goals.
          My largest contribution was extracting and combining embedded retweets in order to form time series of user interaction metrics (likes, coments, retweets) since the Decahose dataset was a snapshot of tweets at creation.
      - title: Volunteer Teacher
        company: Microsoft TEALS Program
        startDate: June 2021
        endDate: Present
        location: Virtual, MI
        learnMoreText: Learn more about the TEALS Program
        learnMoreLink: https://www.microsoft.com/en-us/teals
        description: >
          Technology Education and Literacy in Schools, or TEALS, is a program run by Microsoft whose mission is to build sustainable computer science programs in high schools. You can learn more about the program <a href="https://www.microsoft.com/en-us/teals">here</a>.
          In a team of five, I taught fundamentals of computer science to a class of 17 high schoolers using Snap! and Python programming languages. With my team, we adapted and formulated lesson plans, lab materials, and projects with a teaching team for a year of class.
          We guided and mentored students to build their programming, debugging, and problem-solving skills so that they would be ready for their next step in computer science.
      - title: Teacher Assistant
        company: Michigan Ross School of Business
        startDate: September 2022
        endDate: May 2023
        location: Ann Arbor, MI
        description: >
          I worked as a teacher assistant for Dr. Sanjeev Kumar for undergraduate and graduate classes:
          TO 414 Advanced Analytics For Management Consulting; TO 567 Data Mining and Applied Multivariate Analysis; TO 628 Advanced Big Data Analytics.
          I helped by grading projects and giving feedback. 
          Most importantly, I helped advanced students' understanding of class content through in-class assistance and out of class assistance through office hours.
      - title: General Member
        company: Michigan Finance and Mathematics Society @ University of Michigan
        startDate: January 2020
        endDate: May 2022
        location: Ann Arbor, MI
        description: >
          MFAMS is a club at Michigan that is focused on using math and computation in finance. Many of the meetings
          are education based, furthering my knowledge of computational finance outside of class. Through the club,
          I've leveraged qualitative and quantitative data to create and present stock pitches for the club to invest and add to its portfolio.
          I've also been able to apply financial, mathematical, and statistical models.
      - title: General Member
        company: HackBlue @ University of Michigan
        startDate: January 2020
        endDate: May 2021
        location: Ann Arbor, MI
        description: >
          HackBlue is a club at U of M focused on driving interest in computer science in underprivileged middle schools around the Ann Arbor area.
          I helped design programming lessons tailored to the students to be engaging, fun, and educational and, with a team,
          rebuilt the HackBlue website using HTML, CSS, and JavaScript to better serve the organization’s mission.
    projects:
      - title: TODO
      - link: TODO
      - description: TODO
    education:
      - name: University of Michigan
        gpa: 3.665
        startDate: August 2018
        endDate: April 2023
        colleges:
          - name: College of Literature, Science, and the Arts
            degree: Bachelor of Science, Computer Science
          - name: Stephen M. Ross School of Business
            degree: Bachelor of Business Administration
      - name: Bishop Foley Catholic High School
        gpa: 3.98
        startDate: August 2014
        endDate: May 2018
